services:
  ollama:
    image: 'ollama/ollama:latest'
    ports:
      - '11434'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
  vosk-server:
    image: 'alphacep/kaldi-en:latest'
    ports:
      - '2700:2700'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: 'unless-stopped'
