spring:
  application:
    name: service-api
  ai:
    openai:
      api-key: 11111
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update
  jackson:
    property-naming-strategy: SNAKE_CASE
  flyway:
    locations: classpath:/db/migration
    schemas: public
    baselineOnMigrate: true
    enabled: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mydatabase?currentSchema=mydatabase
    username: myuser
    password: secret

app:
  assistants:
    enabled: false
  quiz:
    enabled: true

